name: Restart Codespace Processes
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"  # (Optional: this schedules it every 3 hours)
jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Restart PM2 Processes
        run: |
          echo "Restarting processes..."
          # Optionally, include any commands that should run on restart.
          # For example, you can re-launch your PM2 processes here.
